let internet;
let username;
let isAdmin = false;
let isClient = false;
const Onlineimas = [];
const Offlineimas = [];
let ArticleFromPhone = [];
let connected = false;
let annoncePers = [];
let ArticleFromPhoneSearch = [];
let isExaminating = false;
let isArticle = false;
let isVendu = false;
let isCommande = false;
let isFinis = false;
let isPeoples = false;
let adMinurl = 'admini';
let ChoosenColor = [];
let AutoChoosenColor = "";
